apiVersion: v1
kind: Service
metadata:
  name: {{ include "eks-demo.fullname" . }}
  labels:
    {{- include "eks-demo.labels" . | nindent 4 }}

spec:
  type: ClusterIP

  selector:
    {{- include "eks-demo.selectorLabels" . | nindent 4 }}

  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
