apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eks-demo.fullname" . }}
  labels:
    {{- include "eks-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "eks-demo.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "eks-demo.selectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: {{ .Chart.Name }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}

            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
